Fix script format

diff --git a/scripts/build-common b/scripts/build-common
--- a/scripts/build-common
+++ b/scripts/build-common
@@ -2,9 +2,9 @@
 set -e
 
 if [[ "$KERNEL_TAG" == "" ]]; then
-	echo "ERROR: Please set the KERNEL_TAG (the mainline KERNEL version is also the git tag) you're building"
-	echo "       e.g., KERNEL_TAG=4.9.10 make release"
-	exit 1
+    echo "ERROR: Please set the KERNEL_TAG (the mainline KERNEL version is also the git tag) you're building"
+    echo "       e.g., KERNEL_TAG=4.9.10 make release"
+    exit 1
 fi
 
 : ${ARTIFACTS:=$(pwd)/assets}
diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -3,8 +3,8 @@
 cd $(dirname $0)/..
 
 if ! ./scripts/ci; then
-	echo "build failure see release.log"
-	exit 1
+    echo "build failure see release.log"
+    exit 1
 fi
 
 echo
diff --git a/scripts/test-firmware b/scripts/test-firmware
--- a/scripts/test-firmware
+++ b/scripts/test-firmware
@@ -13,24 +13,24 @@ echo "FIRMWARE test: $FIRMWARE"
     cd linux-firmware
 
     for i in $(<$FIRMWARE); do
-            if [ -e $i ]; then
-		glob=$(echo $i | sed 's/^\(.*\)-\([^-]*\)\.\([^.]*\)/\1-*.\3/')
-                #echo Found $i, trying $glob
-		latest=$(ls $glob | xargs -n1 -I{} -- git log -1 --format="%ai {}" {} | sort | tail -n1 | cut -d " " -f4)
-		if [ "$latest" != "$i" ]; then
-			echo "ERROR: Firmware $i in $FIRMWARE is not the latest - update to $latest"
-			STOP="1"
-			echo $latest >> new-firmware
-		else
-			echo $i >> new-firmware
-		fi
+        if [ -e $i ]; then
+            glob=$(echo $i | sed 's/^\(.*\)-\([^-]*\)\.\([^.]*\)/\1-*.\3/')
+            #echo Found $i, trying $glob
+            latest=$(ls $glob | xargs -n1 -I{} -- git log -1 --format="%ai {}" {} | sort | tail -n1 | cut -d " " -f4)
+            if [ "$latest" != "$i" ]; then
+                echo "ERROR: Firmware $i in $FIRMWARE is not the latest - update to $latest"
+                STOP="1"
+                echo $latest >> new-firmware
             else
-                echo WARNING: Firmware listed in $FIRMWARE Not found $i
+                echo $i >> new-firmware
             fi
+        else
+            echo WARNING: Firmware listed in $FIRMWARE Not found $i
+        fi
     done
 
 if [ "$STOP" != "" ]; then
-	echo "Update the $FIRMWARE file:"
-	cat new-firmware
-	exit 1
+    echo "Update the $FIRMWARE file:"
+    cat new-firmware
+    exit 1
 fi
