fix the error exiting, and use the Makefile logging
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -2,7 +2,10 @@
 
 cd $(dirname $0)/..
 
-./scripts/ci 2>&1 | tee build.log
+if ! ./scripts/ci; then
+	echo "build failure see release.log"
+	exit 1
+fi
 mv build.log dist/
 
 echo
